### PR TITLE
Check for root and new option

### PR DESCRIPTION
**Pull request by cecio**
If you are interested, I added a couple of things:
- a check for root capabilities: if not running as root it may miss hits, without warning
- a 'deep' mode to scan for the jndi class in all .jar files.

If this is not of interest, just close the pull request ;-) . Thanks!

### CODE REVIEW

**Comment by doronshemtov** [comment]
Hi,
Thanks for sharing :)

I agree regarding the EUID check, there should be a warning.

Regarding the "deep" mode, could you please elaborate on the case when the jndi class is present in a jar that is not log4j-core?
The current scan is looking for the jndi class when log4j-core jar is loaded explicitly or when log4j-core is embedded in the app's jar.

**Comment by cecio** [comment]
Hello!

Thanks for asking!

I'll describe you the case:

if for example an application is compiled with Maven (with default values), the library is included into the final jar without the name `log4j-core`, but the jar is directly expanded into the package.
In this way the tool is missing the entry. You can test it also with the sample docker at ~~https://github.com/christophetd/log4shell-vulnerable-app.git (using gradle)~~ (see comment below).

If you need any further info, just let me know.

Thanks for the tool, great idea!

**Comment by cecio** [comment]
Sorry, I gave you the wrong example. The one reported before is ok. This is one where the usual scan is not working:
https://github.com/leonjza/log4jpwn.git

**Comment by doronshemtov** [comment]
Thank you so much for the feedback!

Since I want to support this case by default, I will include it in a new version I'm working on.
I will also add the EUID check.

BTW, the sample container you provided was very helpful :)

**Comment by doronshemtov** [comment]
Hi,

I have released a new version:
https://github.com/intezer/log4jscan/releases/tag/v1.2.0

The new version is able to detect log4j-core when it is embedded in a jar built with Maven (like the sample you have provided).
FYI, I was able to extract the version from the pom.properties file using `unzip`.

In addition, the new version will display a warning if it was executed without root privileges.

Thank you for reporting these issues.

I will close this pull request, but feel free to reach out if you encounter any issue or if you have additional feedback :)

**Pull request closed without merging**
